@api = http://127.0.0.1:3000/api/inventory/products

POST {{api}}
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3MjBmN2I3OGFjMWI0Y2UyZWYzNTNkNCIsInVzZXJuYW1lIjoicm9vdCIsInJvbGUiOiJyb290IiwiaWF0IjoxNzMwNDk2MzE2LCJleHAiOjE3MzA1ODI3MTZ9.rPbec4PSaA4qo-eE3u2ZkutSFccwo8xpi7Pt-8PnURk
Content-Type: application/json

{
    "nombre": "Nokia XR20 general",
    "descripcion": "Un teléfono robusto diseñado para durar, con cámara dual de 48MP y pantalla de 6.67 pulgadas, ideal para actividades al aire libre.",
    "precio": 499.99,
    "monedaId": "671342d4664051db7c1f8792",
    "grupoId": "671aca0ea6e0841fd34fde57",
    "stock": 30,
    "puntoReCompra": 10
}


### Productos
GET {{api}}/repeated-product
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3MjBmN2I3OGFjMWI0Y2UyZWYzNTNkNCIsInVzZXJuYW1lIjoicm9vdCIsInJvbGUiOiJyb290IiwiaWF0IjoxNzMwNTkwNzY2LCJleHAiOjE3MzA2NzcxNjZ9.g42ooztO7s34cTBti5ZMnaSeo94De5ZqWlnPYdsaNtw
Content-Type: application/json

### Producto en transito
GET {{api}}/67133f450dcdd2f9ee534c5c/transit
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3MGI2YzExYmY1Y2IyZmFlZjE2YjAzZiIsInVzZXJuYW1lIjoiQ2FybG9zIGd1dGhlciIsInJvbGUiOiJyb290IiwiaWF0IjoxNzI5OTI5ODcyLCJleHAiOjE3Mjk5MzM0NzJ9.OjC2Da3SZ1hWrt5rCPF7yeP5G0g5cz5cpsLhjqhKE1M
Content-Type: application/json


### Producto en transito
PATCH  {{api}}/restore
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3MjBmN2I3OGFjMWI0Y2UyZWYzNTNkNCIsInVzZXJuYW1lIjoicm9vdCIsInJvbGUiOiJyb290IiwiaWF0IjoxNzMwNTkwNzY2LCJleHAiOjE3MzA2NzcxNjZ9.g42ooztO7s34cTBti5ZMnaSeo94De5ZqWlnPYdsaNtw
Content-Type: application/json