@api = http://127.0.0.1:3000/api/users

@api2 = http://127.0.0.1:3000/api/auth

### ingresar usuario
POST {{api}}
Content-Type: application/json

{
    "username":"root",
    "password":"1234",
    "role":"root"
}

### login
POST {{api}}/login
Content-Type: application/json

{
    "username":"root",
    "password":"1234"
}

##obtner profile
####
GET {{api}}
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3MGI2YzExYmY1Y2IyZmFlZjE2YjAzZiIsInVzZXJuYW1lIjoiQ2FybG9zIGd1dGhlciIsInJvbGUiOiJDYWplcm8iLCJpYXQiOjE3Mjg4MDMxNzMsImV4cCI6MTcyODgwNjc3M30.BvEpVr8LdDHJ5u3HQE1qRNoocYbfNo3XxAqqWF5ena8